import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Space Tourism</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex flex-col lg:flex-row  justify-between items-center lg:mx-40 lg:mt-40">
          <div className="text-center lg:text-left my-24 mx-20 md:mx-40 lg:mx-10 lg:basis-3">
            <h1 className=" uppercase text-gray-300 mb-7">
              so, you want to travel to
            </h1>
            <h1 className=" uppercase text-white text-8xl xl:text-9xl font-light mb-7">
              space
            </h1>
            <p className="text-slate-300 leading-8 lg:text-lg">
              Let’s face it; if you want to go to space, you might as well
              genuinely go to outer space and not hover kind of on the edge of
              it. Well sit back, and relax because we’ll give you a truly out of
              this world experience!
            </p>
          </div>

          <button className="bg-white rounded-full w-48 h-48 font-light text-3xl uppercase hover:bg-gray-800 hover:text-white flex-initial">
            <Link href="/">Explore</Link>
          </button>
        </div>
      </main>
    </>
  );
}
